name: hisotrl-sb3
channels:
  - defaults
#  - pytorch
dependencies:
  - python=3.8.12
  - pytorch::pytorch=1.10.2
  - pytorch::torchvision=0.11.3
  - cudatoolkit=11.3.1
  - numpy=1.21.2
  - ipykernel=6.19.2
  - jupyter=1.0.0
  - shapely=1.7.1
  - matplotlib
  - pip
#   - pip:
#     - gym
#     - tensorboard
#     - openslide-python
#     - opencv-python
